version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: |
            docker build -t testokur-legacy:latest .
            docker save -o testokur-legacy.tar testokur-legacy:latest            
      - run:
          name: Copy image to server
          command: |
            scp -q testokur-legacy.tar $SSH_USERNAME@$SSH_HOST:/home/docker-images/
  deploy-qa:
    machine: true
    steps:
      - checkout
      - run:
          name: Run container
          command: |
            ssh -q $SSH_USERNAME@$SSH_HOST 'bash -s' < deploy.sh
  deploy-prod:
    machine: true
    steps:
      - checkout
      - run:
          name: Run container
          command: |
            ssh -q $SSH_USERNAME@$SSH_HOST 'bash -s' < deploy-prod.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/